version: '3.9'

services:
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    ports:
      - 3001:3000
    environment:
      CLIENT_URL: http://localhost:3000
      DB_CONNECTION: mongodb://mongo_db:27017
    depends_on: 
      - mongo_db
    volumes:
      - ./server:/app 
      - /app/node_modules

  client:
    build: ./client
    ports:
      - 3000:8080
    environment:
      VITE_API_URL: http://localhost:3001
    depends_on: 
      - mongo_db
      - server
    volumes:
      - ./client:/app 
      - /app/node_modules

volumes:
  mongo_data: {}
